name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem

          # Add EC2 host key to known_hosts to prevent manual prompt
          ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts

          cat >>~/.ssh/config <<END
          Host aws
          HostName $SERVER_HOST
          User $SERVER_USERNAME
          IdentityFile ~/.ssh/key.pem
          StrictHostKeyChecking no
          END

      - name: Copy application files
        run: |
          # Exclude unnecessary files (e.g., .git, .github, venv)
          rsync -avz -e "ssh -i ~/.ssh/key.pem" \
            --exclude .git \
            --exclude .github \
            --exclude venv \
            --exclude __pycache__ \
            ./ ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:~/fastapi-app/

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/key.pem ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd ~/fastapi-app

            # Install necessary packages
            sudo apt-get update
            sudo apt-get install -y python3-venv python3-pip nginx

            # Set up and activate virtual environment
            python3 -m venv venv
            source venv/bin/activate

            # Upgrade pip and install dependencies
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install uvicorn

            # Create a systemd service file for FastAPI
            sudo tee /etc/systemd/system/fastapi.service << 'EOL'
            [Unit]
            Description=FastAPI application
            After=network.target

            [Service]
            User=${{ secrets.SERVER_USERNAME }}
            WorkingDirectory=/home/${{ secrets.SERVER_USERNAME }}/fastapi-app
            ExecStart=/home/${{ secrets.SERVER_USERNAME }}/fastapi-app/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000
            Restart=always

            [Install]
            WantedBy=multi-user.target

            # Setup Nginx configuration
            sudo tee /etc/nginx/sites-available/fastapi << 'EOL'
            server {
                listen 80;
                server_name ${{ secrets.SERVER_HOST }};

                location / {
                    proxy_pass http://127.0.0.1:8000;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                }
            }

            # Enable the Nginx configuration
            sudo ln -sf /etc/nginx/sites-available/fastapi /etc/nginx/sites-enabled/
            sudo rm -f /etc/nginx/sites-enabled/default

            # Test Nginx configuration
            sudo nginx -t

            # Start and enable services
            sudo systemctl daemon-reload
            sudo systemctl enable fastapi
            sudo systemctl restart fastapi
            sudo systemctl restart nginx

            # Verify services are running
            sudo systemctl status fastapi
            sudo systemctl status nginx
          EOF
